名称 :安卓CI

在 :
推 :
分支 : [“主人” ]
牵引请求 :
分支 : [“主人” ]

工作 :
建造 :

在上运行 :ubuntu最新

步骤 :
 -使用 :行动/签出@v3
 -名称 :设置JDK 11
使用 :行动/设置-java@v3
具有 :
java版本 : &#39;11&#39;
分布 : “提姆林”
隐藏物 :格拉德尔

 -名称 :授予gradlew的执行权限
运行 : chmod x梯度
 -名称 :使用渐变构建
运行 :./gradlew版本
